### ISSUE TITLE
Intuition behind the relationship of non-overlapping reads

### ISSUE THREAD

**Issue by Griffan** [shoryaconsul/XHap#4]
Hi @shoryaconsul, nice paper on the XHap! It's unexpected that transformer can even capture relationship/information that exists among non-overlapping reads. Do you have any insights on:

1. What's your explanation/intuition behind this captured hidden information that regular tools ignored or cannot capture.
2. Are there any allele specific features other than sequence content captured by multi-head attention module?
3. On your testing dataset, have you checked if there is homology among distant regions that potentially bridged the non-overlapping relationship?

Thanks again for the excellent work. Looking forward to understanding more of your read embedding work!

**Comment by shoryaconsul** [comment]
Hi @Griffan! I am happy to hear that you enjoyed our paper. As for your questions:

1. Regular tools are limited on the types of relations they can infer between reads as they rely solely on overlapping reads and the concordance/discordance in the overlapping sections of these reads. On the other hand, XHap, seeks to infer these relations (referred to as read correlations in the manuscript), enroute to assembling complete haplotypes. In practice, we observe that the inference of these relations happens through two means: (a) propagating correlations between overlapping read pairs to non-overlapping read pairs and (b) inferring hitherto unseen correlations that improve the clustering (and consequently reconstructed haplotypes). We demonstrate this in Figure 4.
2. In the current formulation, XHap embeds each read into a latent space through the use of a convolutional encoder, so the information across the SNP positions is "blended" together in this embedding. To learn allele-specific features, one would have to either use an embedding that preserves SNP information or directly use the read representation as input to the transformer encoder.
3. The inferred read correlations are semantically meaningful in that they summarize whether a pair of reads originate from the same haplotype or not. Hence, we did not check for homology among the distinct regions, though it may be possible that some non-overlapping read pairs with high values of read correlations exhibit homology.
